seed: 1234

experiment_name: "rand90_logit_50"

num_nodes: 1
gpus: 4

encoder: "clip"
baseclip_type: "RN50"
device: "cpu"
loss_type: "mse"
reconstruction: "adjoint"
training_labels: "clip"

distortion: "randommask"
fixed_mask: False
percent_missing: 0.90
sketch_size: 50

lr: 0.00005
weight_decay: 0.0001
sharpening: 1000
loss_tau: 0.1

dataset: "Imagenet-100"
num_classes: 100
subset_file_name: "imagenet100.txt"

dataset_dir: "/tmp/imagenet100"
logdir: "/tmp"

batch_size: 80

workers: 12

distributed_backend: "ddp"

#training
max_epochs: 25
log_save_interval: 25 #set this to be equal to num_epochs if row_log_interval is 1
row_log_interval: 1
sync_bn: True

#validation
check_val_every_n_epoch: 1
