seed: 1234

experiment_name: "rand90_logit_none_full_long"

num_nodes: 1
gpus: 4

encoder: "clip"
baseclip_type: "RN101"
device: "cpu"
loss_type: "mse"
reconstruction: "lasso"
training_labels: "clip"

distortion: "randommask"
fixed_mask: False
percent_missing: 0.9
sketch_size: "None"

lr: 0.0001
weight_decay: 0.0001
sharpening: 1000
loss_tau: 0.1

dataset: "Imagenet"
num_classes: 1000

dataset_dir: "/tmp/imagenet_subsampled"
logdir: "/tmp"

batch_size: 200

workers: 12

distributed_backend: "dp"

#training
max_epochs: 90
log_save_interval: 90 #set this to be equal to num_epochs if row_log_interval is 1
row_log_interval: 1
sync_bn: True

#validation
check_val_every_n_epoch: 1
