seed: 1234

experiment_name: "rand90_logit_none_full_rn50"

num_nodes: 1
gpus: 1

encoder: "clip"
baseclip_type: "RN50"
device: "cpu"
loss_type: "mse"
reconstruction: "adjoint"
training_labels: "clip"

distortion: "randommask"
fixed_mask: False
percent_missing: 0.9
sketch_size: "None"

lr: 0.001
weight_decay: 0.0001
sharpening: 1000
loss_tau: 0.1

dataset: "Imagenet"
num_classes: 1000

dataset_dir: "/tmp/imagenet_subsampled"
logdir: "/tmp"

batch_size: 64

workers: 12

distributed_backend: "dp"

#training
max_epochs: 50
log_save_interval: 50 #set this to be equal to num_epochs if row_log_interval is 1
row_log_interval: 1
sync_bn: True

#validation
check_val_every_n_epoch: 1
