seed: 1234

experiment_name: "randomforwardop"

num_nodes: 1
gpus: 4

encoder: "clip"
baseclip_type: "RN101"
device: "cpu"
loss_type: "mse"

distortion: "randomforwardop"
fixed_mask: False
percent_missing: 0.9

lr: 0.0003
weight_decay: 0.0001
loss_tau: 0.1
logit_scale: 0.07

dataset: "Imagenet-100"
num_classes: 100
subset_file_name: "imagenet100.txt"

dataset_dir: "/tmp/imagenet100"
logdir: "/tmp"
mapping_and_text_file: "./mapping_text_labels_imagenet100.pkl"
save_mapping_and_text: False

batch_size: 256

workers: 32

distributed_backend: "dp"

#training
max_epochs: 5
log_save_interval: 5 #set this to be equal to num_epochs if row_log_interval is 1
row_log_interval: 1
sync_bn: True
gradient_clip_val: 0.5

#validation
check_val_every_n_epoch: 1
